insert into public.tests (
  title,
  slug,
  description,
  is_free,
  is_published,
  items,
  created_by
)
values (
  'Benzinger - Perfil de funcionamiento',
  'benzinger-perfil-funcionamiento',
  'Cuestionario de autoobservación sobre preferencias de pensamiento, acción y aprendizaje.',
  true,
  false,
  $$[
    {"id":"benzinger-01","question":"¿Eres ordenado y encuentras satisfacción en seguir rutinas y procedimientos establecidos?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-02","question":"¿Eres espiritual y sigues tus sentimientos e instintos?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-03","question":"¿Eres innovador, imaginas cómo será tu vida y te aburres con facilidad?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-04","question":"¿Eres analítico y piensas de manera lógica? ¿Te sientes un líder natural?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-05","question":"Al resolver un problema, ¿confías en tus presentimientos e intuición?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-06","question":"Algunas de mis mejores ideas aparecen cuando no estoy haciendo nada en particular.","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-07","question":"¿Observas automáticamente el rostro de la persona con la que hablas?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-08","question":"¿Te disgustan las tareas o actividades rutinarias?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-09","question":"¿Terminas tus tareas puntualmente y de manera ordenada?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-10","question":"¿Te gusta tocar a las personas para animarlas o expresarles tus sentimientos?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-11","question":"¿Son la cooperación y la armonía los valores humanos más importantes para ti?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-12","question":"¿Son la novedad, la originalidad y la evolución tus valores más importantes?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-13","question":"¿Son tus relaciones humanas la parte más importante de tu vida?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-14","question":"¿Para ti pensar es más importante que sentir?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-15","question":"¿Son muy importantes para ti el desarrollo personal y el crecimiento?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-16","question":"¿Son importantes para ti las reglas y consideras que deben cumplirse?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-17","question":"¿Son los sentimientos más verdaderos e importantes que los pensamientos para ti?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-18","question":"¿Para ti el éxito depende de la experiencia y la perseverancia?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-19","question":"¿Disfrutas conversar, escuchar problemas y compartir consejos?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-20","question":"¿Disfrutas las tareas en las que tienes que clasificar, archivar y planificar?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-21","question":"¿Disfrutas tener rutinas diarias?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-22","question":"¿Te gustan el orden y la organización de tus cosas?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-23","question":"¿Para ti el éxito se mide por los resultados?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-24","question":"¿Se te ocurren constantemente ideas innovadoras y soluciones creativas?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-25","question":"¿Te gusta organizar perfectamente tu habitación y planificar tus tareas de clase?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-26","question":"¿No prestas atención a los detalles?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-27","question":"¿Te consideras una persona lógica?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-28","question":"¿Te consideras una persona conservadora y tradicional?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-29","question":"¿Eres un líder fuerte, decidido y eficaz?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-30","question":"¿Eres una persona muy espiritual?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-31","question":"¿Te gusta delegar y dar órdenes?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-32","question":"¿Te gustan las matemáticas y las ciencias?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-33","question":"¿Te gusta construir y reparar objetos?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-34","question":"¿Te gusta motivar positivamente a los demás?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-35","question":"¿Te gusta mantener las cosas organizadas?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-36","question":"¿Eres puntual y te gusta cumplir con las fechas límite?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-37","question":"¿Te gusta sintetizar y proponer ideas nuevas?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-38","question":"¿Te disgustan la ambigüedad y la falta de previsión?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-39","question":"¿Disfrutas los debates y las discusiones verbales?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-40","question":"¿Te encanta cantar, bailar y escuchar música?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-41","question":"¿Te entusiasman las ideas nuevas y extrañas?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-42","question":"¿Te gustan el pensamiento crítico y el análisis?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-43","question":"¿Te gusta trabajar en los detalles?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-44","question":"¿Eres empático y conectas con los sentimientos de los demás?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-45","question":"¿Te sientes incómodo en situaciones de conflicto?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-46","question":"¿Realizas mejor tus tareas con instrucciones y procedimientos claros?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-47","question":"¿Te gusta programar todo lo que vas a hacer en tu vida?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-48","question":"¿Prefieres a las personas que pueden controlar sus emociones?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-49","question":"¿Te gusta tomar decisiones y tener la última palabra?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-50","question":"¿Te gusta organizar tu dinero y planificar tus gastos?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-51","question":"¿Te gusta hacer varias cosas al mismo tiempo?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-52","question":"¿Prestas siempre atención al movimiento corporal de la persona con la que hablas?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-53","question":"¿Expresas tus ideas con claridad y mucha energía?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-54","question":"¿Quieres saber cómo se sienten los demás?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-55","question":"¿Lees siempre las instrucciones antes de armar un objeto?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-56","question":"¿Eres confiable y disciplinado?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-57","question":"¿Te gusta organizar documentos e información importante?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-58","question":"¿Te gusta que cada cosa tenga un lugar específico?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-59","question":"¿Tienes habilidad para resolver problemas manuales?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-60","question":"¿Tienes talento artístico?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-61","question":"¿Tu sentido del humor te ha causado varios problemas?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-62","question":"¿Usas metáforas y analogías visuales para explicar lo que piensas?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-63","question":"¿Resuelves los problemas uno por uno y paso a paso?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]},
    {"id":"benzinger-64","question":"¿Te consideras una persona racional y eficaz?","type":"single_choice","options":[{"id":"yes","text":"Sí"},{"id":"no","text":"No"}]}
  ]$$::jsonb,
  null
)
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  items = excluded.items,
  is_free = excluded.is_free,
  is_published = excluded.is_published,
  updated_at = now();
